# Generated by Django 4.1.1 on 2022-09-07 08:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('date_of_death', models.DateField(blank=True, null=True, verbose_name='Died')),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the book.', max_length=50)),
                ('isbn', models.CharField(help_text='A 13 characters length unique id.<a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>', max_length=13, unique=True, verbose_name='ISBN')),
                ('summary', models.TextField(help_text='A brief summary of the book.', max_length=100)),
                ('copies', models.IntegerField(default=0, help_text='No of copies Available.')),
                ('author', models.ForeignKey(help_text='Author of the book.', on_delete=django.db.models.deletion.CASCADE, to='catalog.author')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(help_text='Genere of the Book.', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Lang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(default='Eng', max_length=5, verbose_name='Language')),
            ],
        ),
        migrations.CreateModel(
            name='BookInstance',
            fields=[
                ('instanceId', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular book across whole library', primary_key=True, serialize=False)),
                ('imprint', models.CharField(max_length=200)),
                ('due_back', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('1', 'Maintenance'), ('2', 'On loan'), ('0', 'Available'), ('3', 'Reserved')], default='1', help_text='Status of the Instance.', max_length=1)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='catalog.book')),
            ],
            options={
                'ordering': ['due_back'],
            },
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(help_text='Genere of the book.', to='catalog.genre'),
        ),
        migrations.AddField(
            model_name='book',
            name='lang',
            field=models.ForeignKey(help_text='Language of the book.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.lang'),
        ),
    ]
