# Generated by Django 4.1.1 on 2022-09-09 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_bookinstance_borrower'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='status',
            field=models.CharField(choices=[('m', 'Maintenance'), ('2', 'On loan'), ('a', 'Available'), ('3', 'Reserved')], default='1', help_text='Status of the Instance.', max_length=1),
        ),
    ]
